[build-system]
requires = ["setuptools>=67", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cpd-exploratory"
version = "0.3.0"
description = "Computational Protein Design – Exploratory Demo"
readme = "README.md"
license = "Apache-2.0"
authors = [
  { name="Prabin Kumar" }
]
requires-python = ">=3.9"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
