name: Python application (CPD Demo)

on:
  push:
    branches: ["SRC"]
  pull_request:
    branches: ["SRC"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install package
        run: pip install -e .

      - name: Run benchmark
        run: python benchmarks/runtime_benchmark.py
